# Generated by Django 5.0.3 on 2026-03-23 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_expense_category_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_fk',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.category'),
        ),
    ]
